package propertyrenting.user.enumeration;

public enum PermissionType {

    PROPERTY_TYPE_CREATE,
    PROPERTY_TYPE_OVERVIEW,
    PROPERTY_REGISTER,
    PROPERTY_DELETE,
    MY_PROPERTY_OVERVIEW,
    PROPERTY_RATING_UPDATE,
    PROPERTY_GET_BY_RATING,
    PROPERTY_GET_BY_BOOKINGS,
    AD_CREATE,
    AD_DELETE,
    PROPERTY_DELETE_CHECK,
    AD_GET_ACTIVE,
    AD_GET_INACTIVE,
    PROPERTY_INFO_CREATE,
    PROPERTY_INFO_UPDATE_RATING,
    AD_RATE,
    USER_OVERVIEW,
    USER_BLOCK,
    USER_UNBLOCK,
    COMMENT_CREATE,
    COMMENT_ACCEPT,
    COMMENT_DENY,
    COMMENT_GET_PENDING,
    COMMENT_GET_ACCEPTED,
    MESSAGE_CREATE,
    MESSAGE_GET_BY_REQUEST

}
