package propertyrenting.user.enumeration;

public enum PermissionType {

    PROPERTY_TYPE_CREATE,
    PROPERTY_TYPE_OVERVIEW,
    PROPERTY_REGISTER,
    PROPERTY_DELETE,
    MY_PROPERTY_OVERVIEW,
    PROPERTY_RATING_UPDATE,
    PROPERTY_GET_BY_RATING,
    PROPERTY_GET_BY_BOOKINGS,
    AD_CREATE,
    USER_OVERVIEW,
    USER_BLOCK,
    USER_UNBLOCK

}
